# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Linting"
on:
  pull_request:
    branches:
      - fast-dev
      - fast-dev-gke
      - master
    tags:
      - ci
      - lint

jobs:
  boilerplate:
    name: Boilerplate check
    uses: ./.github/workflows/run-tool.yaml
    with:
      run: |
        python3 tools/check_boilerplate.py $GITHUB_WORKSPACE

  terraform-fmt:
    name: Terraform linting check
    uses: ./.github/workflows/run-tool.yaml
    with:
      run: |
        terraform fmt -recursive -check -diff $GITHUB_WORKSPACE

  documentation-fabric:
    name: Check documentation (fabric)
    uses: ./.github/workflows/run-tool.yaml
    with:
      run: |
        python3 tools/check_documentation.py examples modules fast

  documentation-links-fabric:
    name: Check documentation links (fabric)
    uses: ./.github/workflows/run-tool.yaml
    with:
      run: |
        python3 tools/check_links.py .

  name-length-fast:
    name: Check documentation links (fabric)
    uses: ./.github/workflows/run-tool.yaml
    with:
      run: |
        python3 tools/check_names.py --prefix-length=10 fast/stages

  yapf:
    name: Check python formatting
    uses: ./.github/workflows/run-tool.yaml
    with:
      run: |
        yapf --style="{based_on_style: google, indent_width: 2, SPLIT_BEFORE_NAMED_ASSIGNS: false}" -p -d tools/*.py
